import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/components/providers/ReduxProvider";
import axios from "axios";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cks = await cookies();
  const token =  cks.get("token")?.value;
  try {
    const res= await axios.get(`${process.env.BACKEND_API}/user/auth`, {
      headers: {
        Authorization: `bearer ${token}`
      }
    });
    console.log(res);
    
  } catch (err) {
    console.log(err)
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-700`}
      > 
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
